apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: pluscontextbot

spec:
  replicas: 1

  # Pod specification
  template:
    metadata:
      labels:
        run: pluscontextbot
    spec:
      containers:
        - name: web
          image: gcr.io/nyt-games-dev/nyt-plus-context-bot:{{ .COMMIT }}
          env:
          - name: NYT_TOKEN
            value: {{ .NYT_TOKEN }}
          - name: TWT_ACCESS
            value: {{ .TWT_ACCESS }}
          - name: TWT_ACCESS_SECRET
            value: {{ .TWT_ACCESS_SECRET }}
          - name: TWT_CONSUMER
            value: {{ .TWT_CONSUMER }}
          - name: TWT_CONSUMER_SECRET
            value: {{ .TWT_CONSUMER_SECRET }}
