build:
  image: golang:1.7
  commands:
    # copy cert from host
    - cp /etc/ssl/certs/ca-certificates.crt .
    - go get ./...
    - go test -v -cover
    - CGO_ENABLED=0 go build -o bot .
  when:
    event:
      - push
      - pull_request

publish:
  gcr:
    repo: nyt-games-dev/nyt-plus-context-bot
    tag: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_DEV
    storage_driver: overlay
    when:
      event: push
      branch: master

deploy:
  gke:
    image: nytimes/drone-gke
    template: .deployment.yml
    zone: us-central1-a
    cluster: games
    token: >
      $$GOOGLE_CREDENTIALS_DEV
    vars:
      NYT_TOKEN: $$NYT_TOKEN
      TWT_ACCESS: $$TWT_ACCESS
      TWT_ACCESS_SECRET: $$TWT_ACCESS_SECRET
      TWT_CONSUMER: $$TWT_CONSUMER
      TWT_CONSUMER_SECRET: $$TWT_CONSUMER_SECRET
    when:
      event: push
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: games-releases
    username: drone
